version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: majstorica-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: majstorica-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  neo4j:
    image: neo4j:5
    container_name: majstorica-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j-data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: majstorica-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped

volumes:
  mongo-data:
  neo4j-data:
